package com.arghya.passworddatabase.util;

public class PasswordDatabaseConstant {
	public static final String STAR = "***************";
	public static final String PASSWORD = "Password";
	public static final String DATABASE = "Database";
	public static final String LOGIN = "Login";
	public static final String SPACE = " ";
	public static final String LOGO = "*************** Password Database ***************";
	public static final String UNDERLINE = "---------------";
	public static final String USERNAME = "UserName";
	public static final String COLON = ":";
	public static final String UNAME = "argpal";
	public static final String PWRD = "argpal";
	public static final String WRONG_UNAME_PASS = "You have entered wrong username or password.";
	public static final String TO_EXIT = "Press enter to exit...";
	public static final String ADD = "1. Add";
	public static final String UPDATE = "2. Update";
	public static final String DELETE = "3. Delete";
	public static final String DISPLAY = "4. Display";
	public static final String EXIT = "5. Exit";
	public static final String ENTER_SELECTION = "Enter your selection.";
	public static final String WRONG_SELECTION = "Wrong entry!!";
	public static final String FILE_NAME = "PasswordDatabase";
	public static final String FILE_PLACE = "C:\\";
	public static final String FOLDER_NAME = "PasswordDatabase";
	public static final String WEBSITE = "Website";
	public static final String ENC_ALGORITHM = "AES";
	public static final String EMPTY_SPACE = " ";
	public static final String NEW_LINE = "\n";
	public static final String DOT = ".";
	public static final String SERIAL_NO = "SL No.";
	public static final String MODIFICATION_FIELD = "Which field you want to modify?";
	public static final String UPDATED_VALUE = "Please enter updated value";
	public static final String DOUBLE_BACKSLASH = "\\";
	public static final String NO_DATA = "No data found!!!";
	public static final String UPDATION_SUCCESSFUL = "Data has been successfully updated!!!";
	public static final String DELETE_VERBIEAGE = "Are you sure you want to delete this record?";
	public static final String CONFIRMATION_MESSAGE = "Press 'Y' to delete or 'N' revert";
	public static final String DATA_REMOVED = "Data has been removed successfully";
	public static final String DOUBLE_QUOTE = "\"";
	public static final String MAIN_MENU_CODE = "M";
	public static final String DISPLAY_MAIN_MENU = "Press 'M' to go to (M)ain menu.";
	public static final String Y = "Y";
}